const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //admin
    FECH_GENDER_START: 'FECH_GENDER_START',
    FECH_GENDER_SUCCESS: 'FECH_GENDER_SUCCESS',
    FECH_GENDER_FAILED: 'FECH_GENDER_FAILED',

    FECH_POSITION_START: 'FECH_POSITION_START',
    FECH_POSITION_SUCCESS: 'FECH_POSITION_SUCCESS',
    FECH_POSITION_FAILED: 'FECH_POSITION_FAILED',

    FECH_ROLE_START: 'FECH_ROLE_START',
    FECH_ROLE_SUCCESS: 'FECH_ROLE_SUCCESS',
    FECH_ROLE_FAILED: 'FECH_ROLE_FAILED',

    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_FAILED: 'SAVE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FECH_ALLUSER_SUCCESS: 'FECH_ALLUSER_SUCCESS',
    FECH_ALLUSER_FAILED: 'FECH_ALLUSER_FAILED',

    FECH_TOP_DOCTORS_SUCCESS: 'FECH_TOP_DOCTORS_SUCCESS',
    FECH_TOP_DOCTORS_FAILED: 'FECH_TOP_DOCTORS_FAILED',

    FECH_ALL_DOCTORS_SUCCESS: 'FECH_ALL_DOCTORS_SUCCESS',
    FECH_ALL_DOCTORS_FAILED: 'FECH_ALL_DOCTORS_FAILED',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    FECH_DETAIL_DOCTORS_SUCCESS: 'FECH_DETAIL_DOCTORS_SUCCESS',
    FECH_DETAIL_DOCTORS_FAILED: 'FECH_DETAIL_DOCTORS_FAILED',

    FECH_ALLCODES_SCHEDULE_TIME_SUCCESS: 'FECH_ALLCODES_SCHEDULE_TIME_SUCCESS',
    FECH_ALLCODES_SCHEDULE_TIME_FAILED: 'FECH_ALLCODES_SCHEDULE_TIME_FAILED',

    FECH_DOCTOR_SCHEDULE_TIME_SUCCESS: 'FECH_DOCTOR_SCHEDULE_TIME_SUCCESS',
    FECH_DOCTOR_SCHEDULE_TIME_FAILED: 'FECH_DOCTOR_SCHEDULE_TIME_FAILED',

    SAVE_BULK_DOCTOR_SCHEDULE_SUCCESS: 'SAVE_BULK_DOCTOR_SCHEDULE_SUCCESS',
    SAVE_BULK_DOCTOR_SCHEDULE_FAILED: 'SAVE_BULK_DOCTOR_FAILED',

    FECH_ALLCODES_DOCTOR_INFOR_SUCCESS: 'FECH_ALLCODES_DOCTOR_INFOR_SUCCESS',
    FECH_ALLCODES_DOCTOR_INFOR_FAILED: 'FECH_ALLCODES_DOCTOR_INFOR_FAILED',

})

export default actionTypes;